version: '3.9'
services:
  app:
    build: .
    restart: always
    container_name: nekoya_web
    env_file: .env
    environment:
      URL: ${URL}
      HOST: ${HOST}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_TIMEOUT: ${DB_TIMEOUT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
    ports:
      - "9286:9286"